packages:
  - "backend"
  - "frontend"
overrides:
  babel-plugin-istanbul: 8.0.0
  glob: 13.0.6
allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@nestjs/testing@11.1.28"
  - "@eslint-react/ast@5.13.1"
  - "@eslint-react/core@5.13.1"
  - "@eslint-react/eslint-plugin@5.13.1"
  - "@eslint-react/eslint@5.13.1"
  - "@eslint-react/jsx@5.13.1"
  - "@eslint-react/shared@5.13.1"
  - "@eslint-react/var@5.13.1"
  - eslint-plugin-react-dom@5.13.1
  - eslint-plugin-react-jsx@5.13.1
  - eslint-plugin-react-naming-convention@5.13.1
  - eslint-plugin-react-rsc@5.13.1
  - eslint-plugin-react-web-api@5.13.1
  - eslint-plugin-react-x@5.13.1
